---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rating-service-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: '{{ .Values.ingress.host }}'
    http:
      paths:
      - path: /rating
        backend:
          serviceName: rating-service
          servicePort: 8386