apiVersion: v1
kind: Service
metadata:
  labels:
    run: rating-service-deployment
  name: rating-service
spec:
  ports:
  - port: 8386
    protocol: TCP
    targetPort: 8386
  selector:
    run: rating-service-deployment
  sessionAffinity: None
  type: NodePort